name: Test 😎

on:
  pull_request: {}
  push: {}

jobs:
  Build:
    name: Test ${{ matrix.python-version }} 🔑
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.13'
        - '3.14'
        - '3.15'

    steps:
      - uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --frozen
      - name: Lint with Ruff
        run: uv run ruff check adbtool tests

      - name: Test with pytest
        run: uv run pytest
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Test on Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: uv run pytest -v . --durations=0
